### ISSUE TITLE
Stopped working / Entities unavailable after update

### ISSUE THREAD

**Issue by mpikosdimitris** [thecode/ha-rpi_gpio#343]
Hello,

i was using the integration with older versions and this is because when i tried to update to 2024.x.x some months ago, i couldn't make the integration to work again. Today i tried to update again and if something went wrong i would do rollback to the previous version but i cound't make it. I'm using a RPi4 and i have a fan connected to pins 4-6-8 (GPIO 14) and this is my setup in `configuration.yaml` . My entities in version 2024.12.1 are unavailable and in version 2024.12.2 are missing. This is my setup :

HA Core 2025.1.2

```
binary_sensor:
  - platform: rpi_gpio
    sensors:
      - port: 14
        name: "RPi4 FAN"

switch:
  - platform: rpi_gpio
    switches:
      - port: 14
        name: "RPi4 Fan"
```

My previous setup was like : 

```
switch:
  - platform: rpi_gpio
    ports:
       14: RPi4 FAN
```

but even with a rollback i can't make it to work again. Any suggestions please ?

**Comment by tomer-w** [comment]
Hi @mpikosdimitris , sorry for your experience.
With regards to the rollback to old version, I have no idea what is wrong. You will need to provide logs as described in the end of our GitHub page. It should work as the integration don't have any long term memory.

With regards to the new version, this is easier. You don't need both ```binary_sensor``` and ```switch```. You should just keep the `switch` one. Don't forget to restart after you change the configuration file. This will solve the problem. If not, we will need to get the logs to understand the exact situation.

**Comment by mpikosdimitris** [comment]
Thanks for your reply @tomer-w , i do a restart every time i change something in my cofniguration, also tried to reboot my RPi4 with no luck. Finaly i removed the `binary_sensor` and `rpi_gpio:` and `path: /dev/gpiochip0` below my `default_config:` and with version 2024.12.2 the switch entity is missing in integrations page :

![Image](https://github.com/user-attachments/assets/26ca6f8e-0f19-4c55-a2fd-d0bae257437a)

rolling back to version 2024.12.1 entity comes back : 

![Image](https://github.com/user-attachments/assets/1f983f50-cc25-4140-9a3a-3acb26967704)

but the status is Unavailable : 

![Image](https://github.com/user-attachments/assets/0bf0827c-bfc3-46f4-817c-bf70b80c0529)

after that i tried to delete the entity , restart HA , the entity comes back but now i'm facing a new problem...when i trigger the switch i get this error :

![Image](https://github.com/user-attachments/assets/1dbbe0eb-6db9-4fc9-b002-7bcc1d502e9c)

here is my debig log

```
2025-01-20 00:26:08.791 DEBUG (Dummy-1) [custom_components.rpi_gpio.hub] in turn_on 14
2025-01-20 00:26:08.792 ERROR (Dummy-1) [homeassistant.components.websocket_api.http.connection] [2854125608] Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 245, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2795, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2838, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1006, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
        hass, entity, func, data, call.context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1078, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/rpi_gpio/switch.py", line 102, in async_turn_on
    self._hub.turn_on(self._port)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/config/custom_components/rpi_gpio/hub.py", line 172, in turn_on
    self._lines.set_value(port, Value.ACTIVE)
    ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'set_value'
2025-01-20 00:26:10.864 DEBUG (Dummy-1) [custom_components.rpi_gpio.hub] in turn_off 14
2025-01-20 00:26:10.865 ERROR (Dummy-1) [homeassistant.components.websocket_api.http.connection] [2854125608] Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 245, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2795, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2838, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1006, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
        hass, entity, func, data, call.context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1078, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/rpi_gpio/switch.py", line 107, in async_turn_off
    self._hub.turn_off(self._port)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/config/custom_components/rpi_gpio/hub.py", line 177, in turn_off
    self._lines.set_value(port, Value.INACTIVE)
    ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'set_value'

```

revert back to version 2024.12.2 and again the entity is missing again...

**Comment by jocjocde** [comment]
I Have the same problem. 

![Image](https://github.com/user-attachments/assets/349b2628-4690-4d88-b203-b0ebd4b78ce2)

**Comment by tomer-w** [comment]
I will need the debug logs as described here: https://github.com/thecode/ha-rpi_gpio?tab=readme-ov-file#reporting-issues
It should be the full logs from after you restart HA. The initialization part is the most important part.

Thanks,
Tomer.
________________________________

**Comment by jocjocde** [comment]
> I will need the debug logs as described here: https://github.com/thecode/ha-rpi_gpio?tab=readme-ov-file#reporting-issues
> It should be the full logs from after you restart HA. The initialization part is the most important part.
> Please note is be should be from the largest version of the integration. This is the only version we keep updating.

attached the debug file

Thanks

[home-assistant_rpi_gpio_2025-01-20T15-49-23.740Z.log](https://github.com/user-attachments/files/18479713/home-assistant_rpi_gpio_2025-01-20T15-49-23.740Z.log)

**Comment by tomer-w** [comment]
@jocjocde , the important line in the log is the following error: Port 14 already in use by gpio-fan.
Seems you have another component called goio-fan which is using the same GPIO port.

**Comment by mpikosdimitris** [comment]
After updating to 2025.2.0 version the device again disapeared and this is the debug log.

[home-assistant_rpi_gpio_2025-02-01T18-52-05.530Z.log](https://github.com/user-attachments/files/18629976/home-assistant_rpi_gpio_2025-02-01T18-52-05.530Z.log)

**Comment by tomer-w** [comment]
@mpikosdimitris , the relevant error in the log is: ```Port 14 already in use by gpio-fan@0```. You can't use the same GPIO port for this integration and something else.

**Comment by mpikosdimitris** [comment]
This is the only entry in my configuration.yaml , i don't have any other entry :(

```
switch:
  - platform: rpi_gpio
    switches:
      - port: 14
        name: "RPi4 Fan"
```

**Comment by mpikosdimitris** [comment]
![Image](https://github.com/user-attachments/assets/53ecae9e-7527-4558-b4d9-a5a6e9d8139c)

**Comment by mpikosdimitris** [comment]
![Image](https://github.com/user-attachments/assets/24135cf5-0ebd-45ed-8245-697e91413231)

![Image](https://github.com/user-attachments/assets/6944e494-ab7b-4609-8d61-4fa7552ba9f2)

**Comment by tomer-w** [comment]
I don't think this GPIO usage is coming from this integration. You have it defined somewhere else.

**Comment by mpikosdimitris** [comment]
The only configuration for PIN 14 is in raspi-config of my RPi4 and in /boot/config.txt there is an entry `dtoverlay=gpio-fan,gpio_pin=14,temp=60000` . But this is configured for 3-4 years and worked without problem in previous versions. When temperature exceeds 60°C the fan starts automaticaly and also i had the option to turn it on manually from HA or with an automation with other temperature limits.

**Comment by jocjocde** [comment]
![Image](https://github.com/user-attachments/assets/b2b6f80c-d791-4c35-989f-4a5cc9192115)

You were right. I had the fan activated in the operating system.
I have disabled it and it now works correctly.

**Comment by tomer-w** [comment]
@mpikosdimitris , it is true that this worked in previous versions. We had to rewrite the integration to support Raspberry Pi 5 and the new library we are using is trying to get exclusive lock in the GPIO pin. If you are not using RP5, you can safely use the old version which will allow you to use the fan setting in parallel. Another option is to move the triggering of the fan when temp is high to HA automation and remove the other setting.

**Comment by mpikosdimitris** [comment]
It would be nice if you could make it to work again in parallen. The latest version before making changes was 2022.7.0 right ?

**Comment by tomer-w** [comment]
Yes. 2022.7.0 is the last version which use the old GPIO library. There is no plans to improve this. The new RP5 library does not support concurrent usage of the same GPIO line. I don't think they will change that.

**Comment by elsalaoo** [comment]
> ![Image](https://github.com/user-attachments/assets/b2b6f80c-d791-4c35-989f-4a5cc9192115)
> 
> You were right. I had the fan activated in the operating system. I have disabled it and it now works correctly.

hello! i have same problem, how can I enter in rapberry setup to see if my fan is activated?

**Comment by jocjocde** [comment]
Connect via VNC or with a screen, keyboard and mouse to your raspberry. I'll upload some images so you can see where the option is.

![Image](https://github.com/user-attachments/assets/0fcb5e89-7f43-4294-9a55-27f896e19b55)

![Image](https://github.com/user-attachments/assets/95d54c1a-961e-45ac-9986-5ab142407ed7)

**Comment by elsalaoo** [comment]
thanks a lot! I will try it tomorrow and hope it works

**Comment by elsalaoo** [comment]
> Connect via VNC or with a screen, keyboard and mouse to your raspberry. I'll upload some images so you can see where the option is.
> 
> ![Image](https://github.com/user-attachments/assets/0fcb5e89-7f43-4294-9a55-27f896e19b55)
> 
> ![Image](https://github.com/user-attachments/assets/95d54c1a-961e-45ac-9986-5ab142407ed7)

thanks again for your help, I tried to connect via hdmi and it didn't work as I have home assistant OS. But finally when I connect my raspy again the problem disappeared by magic
